class DailyStatusQuotesTr {
  static const List<String> missedPrayers = [
    'Namaz kurtuluştur, bugün ilk dönülecek kapı olsun.',
    'Namaz nefse ağır geliyorsa, bil ki kalp yakınlık istiyordur.',
    'Namazını kıl, günün dolsun, ruhun huzur bulsun.',
    'Rahmet kapısını erteleme, namaz vakti açık bir kapıdır.',
    'Her samimi secde, kalpten uzun bir yorgunluğu siler.',
    'Seninle huzur arasında samimi bir tekbir vardır.',
    'Namazın dönüşü, sonrasının düzelmesinin başlangıcıdır.',
    'Allah seni beş kez çağırıyor, bu çağrıya hazır bir kalple icabet et.',
    'Göğsün daraldığında, ferahlık secdededir.',
    'Namazı, dünya ile pazarlık edilmeyen bir randevu yap.',
    'Namazını korursan, Allah da senin gününün geri kalanını korur.',
    'Namaz, nefsin ilk onarımı ve sebatın en büyük nedenidir.',
    'Namazında samimi olan, etkisini gün boyunca bulur.',
    'Gerçek bir dönüş seccade üzerinden başlar.',
    'Yarının dertlerini yüklenme, bugün namazını hakkıyla kıl.',
    'Secde anında kalbin ağır yükleri yavaşça düşer.',
    'Ruh yorulduğunda, onun ilacı huşu içinde kılınan bir namazdır.',
    'Başarılı olan, namazı gününde kırmızı çizgisi yapandır.',
    'Her ezanı senin için kaçırılmayacak bir rahmet mesajı yap.',
    'Namazın senin sebatının gerçek ölçüsüdür.',
    'Müezzin çağırdığında dünyayı bırak ve Allah\'a yönel.',
    'Namaz, yoğun bir günde kurtuluş köprüsüdür.',
    'Namazı koru, Allah da sana kolaylık kapılarını açsın.',
    'Güçlü bir mümin gününe namazla başlar ve namazla bitirir.',
    'Huzur, farz namazları muhafaza edenin kalbinde barınır.',
    'Kurtuluşunun temelinden: namazdan gafil olma.',
    'Vaktinde kılınan her namaz, Allah\'ın rızasına doğru bir adımdır.',
    'Namazı, sanki dünyayla olan son ahdinmiş gibi kıl.',
    'Namazda kalbin doğruluğu ve yolun güvenliği vardır.',
    'Cennete giden bin millik yolcukluk bir secde ile başlar.'
  ];

  static const List<String> missedDhikr = [
    'Allah’ı an, O da seni ansın; bu kalbe en büyük yetinmedir.',
    'Zikir kalbin hayatıdır, kendini bu hayattan mahrum etme.',
    'Bir dakikalık zikir, tam bir günün huzurunu inşa eder.',
    'Zikirle ıslanan dil ve huzur bulan kalp.',
    'Sabahını ve akşamını Allah ile başlat, Allah ile bitir.',
    'Allah’ı zikretmek en yakın, en kolay ve en kalıcı kaledir.',
    'Kalp huzursuzsa, onu istiğfar ve tesbih ile sabitle.',
    'Zikredenler, amel hafifliği ve etki büyüklüğü ile öne geçerler.',
    'Zikrini artır, Allah’ın izniyle kalbinin nuru artsın.',
    'Subhanallah, paslanmayan bir rahatlık anahtarıdır.',
    'Günlük zikirlerin senin kalendir, onları terk etme.',
    'Allah’ın zikriyle teselli bulan bir kalp ne kadar da yücedir.',
    'Zikrini çoğalt, zamanında bereket bulacaksın.',
    'Allah’ı anarak, meşguliyet ne olursa olsun saatlerin güzelleşir.',
    'İstiğfar, tökezlemeleri siler ve göğsü genişletir.',
    'Her halükarda dilini zikirle diri tut.',
    'Her tesbih, sana nur ve sevap yazar.',
    'Zikre sarılan huzur içinde yaşar.',
    'Bedenin suya ihtiyacı olduğu gibi kalbinin de zikre ihtiyacı vardır.',
    'Sabah ve akşam zikirleri imanın günlük çitidir.',
    'Gününü bir miktar tesbih olmadan geçirme.',
    'Zikreden her an Allah\'a yakındır.',
    'Dünya daralırsa zikre sığın.',
    'Allah\'ı anmak, gafletten sonra kalbi diriltir.',
    'Beni anın, Ben de sizi anayım; seni bekleyen bir çağrı.',
    'Her istiğfar ile sıkıntılar dökülür.',
    'Kalıcı iyilikler, dünyadan ve içindekilerden daha hayırlıdır.',
    'Hayatın koşuşturmacasında, kalıcı iyilikleri ihmal etme.',
    'Samimi bir "La havle" seni bir ömür boyu sıkıntıdan kurtarabilir.',
    'Zikirle kendini güçlendir, çünkü şeytanlar Allah\'ı ananlardan kaçar.'
  ];

  static const List<String> missedWird = [
    'Kuran gününün yoldaşıdır, ondan nasibini terk etme.',
    'Her gün az ayet, büyük bir sebat inşa eder.',
    'Kuran’a devam edenin, Allah gizlisini ve açığını ıslah eder.',
    'Kalbini tilavetin bereketinden, dakikalarca da olsa mahrum etme.',
    'Hıfz adım adımdır, bereket devamlılıktadır.',
    'Günün için en güzel yatırım, ihlasla ezberlediğin bir ayettir.',
    'Her Kuran virdi, yoluna eklenen bir nurdur.',
    'Gününü Mushaf’a bağla, Allah seni fitnelerden korur.',
    'Kuran’ın azı bile, devamlı olursa Allah katında çoktur.',
    'Bugünün ayeti, yarının kurtuluşu olabilir.',
    'Kuran kalplerin baharıdır, onu terk etme.',
    'Kuran\'la geçen her gün nura nur katar.',
    'Ezber bir ayetle başlar ve sebatla büyür.',
    'Bir gün Kuran\'ın senden şikayet etmesine izin verme.',
    'Mushaf, onunla kalana sadık bir arkadaştır.',
    'Ne kadar küçük olursa olsun, kesemeyeceğin bir virde alış.',
    'Kuran nefsi temizler ve yola rehberlik eder.',
    'Devamlılık olmadan ezberde başarı olmaz.',
    'Bugün ezberlenen bir ayet, eylemsiz arzulardan daha iyidir.',
    'Günlük tilavet uzun soluklu bir huzur eker.',
    'Sabahını Kuran\'a bağla, Allah sana sebat versin.',
    'Her gün virdin için sabit bir zaman ayır.',
    'Kuran\'ı seven onunla kalır ve onu terk etmez.',
    'Kuran için programından düşmeyen bir randevu ayarla.',
    'Pınardan uzaklaşma, çünkü Kuran ruhunun suyudur.',
    'Ve Kuran\'ı tertil üzere oku... bunu gününün amacı yap.',
    'Kuran\'a doğru atılan her adım bereketi sana yaklaştırır.',
    'Yaratıcısının sözlerini terk eden için mutluluk yoktur.',
    'Kuran göğüslerdekilere bir şifadır, ilacını nasıl terk edersin?',
    'Sizin en hayırlınız Kuran\'ı öğrenen ve öğreteninizdir... ondan payını al.'
  ];

  static const List<String> perfect = [
    'Gününe güzellikle başlayıp güzellikle bitirene ne mutlu.',
    'Müminler kurtuluşa ermiştir.',
    'Allah’ım kabul et, hayır dolu bir gün.',
    'Şüphesiz iyiler nimet içindedir.',
    'Maşallah, bugünkü sebatın sadakat alametidir.',
    'Devamlılığın büyük bir nimettir, buna şükret.',
    'Bu güzel bir gün, Allah’tan kabul ve devamlılık iste.',
    'Allah’tan bu güzel sebatı bereketlendirmesini dileriz.',
    'Hayır tamamlanınca, Allah’a şükür onu süsler.',
    'İtaatte devamlılık, yakınlığın en güzel kapılarındandır.',
    'İtaatin ve kamil niyetin buluştuğu gün ne güzeldir.',
    'Allah\'tan sana bu güzel sebatı daim kılmasını dileriz.',
    'Bugünkü sebatın bir başarı işaretidir, hamt et.',
    'Eğer bugün iyi yaptıysan, devam et, mükafatın katlanacaktır.',
    'Her tam itaat günü Ahiret için bir dengedir.',
    'Günlük iyi bir son, şükre layık bir nimettir.',
    'Gününü Allah\'a yakınlıkla sonlandırana müjdeler olsun.',
    'Bu sebatı günlük bir ruh hali değil, ömür boyu bir alışkanlık haline getir.',
    'Başarılı kul, az da olsa itaatine devam edendir.',
    'Allah çabalayıp tamamladıklarının mükafatını yazsın.',
    'Bunlar amel defterinde görmekten memnun olacağın günlerdir.',
    'Sürekli yapılan az bir amel, kesintiye uğrayan çok amelden hayırlıdır... ve sen iyi bağlandın.',
    'Güzelliklerin O\'nun lütfuyla tamamlandığı Allah\'a hamdolsun.',
    'Meleklerin göklerde övündüğü bir gün... Allah seni kutsasın.',
    'Eğer şükrederseniz, size nimetimi elbette artırırım... bu nimet için Allah\'a şükret.',
    'Böyle bir gün sana rahmetin ve güzel bir sonun müjdesini verir.'
  ];

  static const List<String> good = [
    'Rabbinizden bir mağfirete koşun.',
    'Allah’ım, zikrine, şükrüne ve güzel ibadetine bize yardım et.',
    'Yarın Allah’ın izniyle başka bir fırsat, durma.',
    'Az kaldı, gününü Allah’a yakınlıkla tamamla.',
    'Gününün bereketi tamamlanmak üzere, basit adımlar kaldı.',
    'Güzel sebat, biraz daha ekle, Allah sana çokça açar.',
    'Bugün iyiydin, iyiliğin devamı daha büyüktür.',
    'Günün geri kalanını sadık bir niyetle değerlendir.',
    'Tamamlanmaya çok yakın, durmadan devam et.',
    'Kalan az, Allah sana kolaylıkla açar.',
    'Birkaç adım ve seçkin bir güne ulaşırsın.',
    'Başladığın şeyi sağlamlaştır, çünkü güzel son yakın.',
    'Gününün geri kalanını itaat üzerine topla, kabul göreceksin.',
    'İşte güzel günler böyledir: gayret ve sebat.',
    'Günün son saatlerini en iyi saatler yap.',
    'Sadece biraz kaldı, geri çekilme.',
    'Günün çoğunda iyi yaptıysan, onu mükemmellikle tamamla.',
    'Gününde hala iyilik için yer var, onu tamamla.',
    'Allah samimi kalbine bakar, o yüzden işi sevgiyle bitir.',
    'En zor kısmı başardın, şimdi durma.',
    'Bugün yaptığın her şey harika, bunu sonunda tembellikle bozma.',
    'Bu akşam iyi işlere koş ki gününün ihtişamı tamamlansın.',
    'İleriye doğru atılan her adım seni Cennet derecelerine yaklaştırır.'
  ];

  static const List<String> average = [
    'Allah’ın rahmetinden ümidinizi kesmeyin, Allah bütün günahları bağışlar.',
    'Her saat, Allah’a dönüş için bir fırsattır.',
    'Allah kulunun tövbesiyle sevinir, şimdi başla.',
    'Yapabildiğinle başla, Allah kendisine yönelen kulu sever.',
    'Yol bir adımla başlar, bugünkü adımın bereketlidir.',
    'Telafi kapısı, günde zaman kaldığı sürece açıktır.',
    'Günün geri kalanını, geçenden daha sadık kıl.',
    'Modunu bekleme, başla ve yardım sana gelir.',
    'Şu an güzel bir başlangıç, sürekli ertelemekten hayırlıdır.',
    'Gelecek her dakika, kaçanı telafi etmek için bir fırsattır.',
    'Olduğun gibi Allah\'a yönel, Allah sana yardım edecektir.',
    'Eğer şimdi başlarsan, bütün gününün şeklini değiştirirsin.',
    'İtaat her zaman yeniden başlar ve kapıları asla kapanmaz.',
    'En iyisi geçmedi, en iyisi şimdi başlıyor.',
    'Allah\'tan yardım iste ve ilk adım için acz içinde olma.',
    'Allah\'a her dönüş hesaba katılır ve sevilir.',
    'Bugün elinde olandan başla, Allah onu bereketlendirecektir.',
    'Gün henüz bitmedi, kaçırdıklarını telafi et.',
    'Gece bir örtüdür ve telafi etmek için bir fırsattır.',
    'Şimdi gününü itaatle onarmak için doğru zaman.',
    'Ortayla yetinme, mümkün olan mükemmelliğe ulaşmak için kendini yükselt.',
    'Kararlılığını uyandır, yine de bu günü harika yapabilirsin.',
    'Bir kötülüğü silmek için onu bir iyilikle itme gücüne sahipsin.'
  ];

  static const List<String> poor = [
    'Şüphesiz Allah çok bağışlayan, çok esirgeyendir, ümitsizliğe kapılma.',
    'Rahmetim her şeyi kuşatmıştır.',
    'Günahtan tövbe eden, hiç günahı olmayan gibidir, Allah’a dön.',
    'Şimdi başla, küçük bir amelle bile olsa, Allah kalbini açar.',
    'Allah’a en yakın yol, dönüşün sadakatidir.',
    'Başlaman yeterli, hayrı tamamlamak Allah’ın lütfundadır.',
    'Zayıflık, Allah’tan çokça yardım istemekle kaybolur.',
    'Ne kadar geç kalsak da bugün yeni bir başlangıçtır.',
    'Kendini bir günle yargılama, yeniden başla.',
    'Rahmet kapısı geniştir, onu tövbe ve amelle aç.',
    'Allah\'a dönmek sadece samimi niyet gerektirir.',
    'Tökezlemeler çok olsa da, Allah merhametlilerin en merhametlisidir.',
    'Az ile başla ve hiçbir itaati küçümseme.',
    'Gerçek değişim bugünün kararıyla başlar.',
    'Şeytanın seni samimi bir başlangıçtan mahrum etmesine izin verme.',
    'Başarılı olan, her gevşediğinde hızla geri dönendir.',
    'İyimser ol, çünkü Allah tövbeyi kabul eder ve tövbe edenleri sever.',
    'Tekrar tekrar günah işlesen de, tekrar tekrar Allah\'a dön.',
    'Allah, bir kulun yüz çevirdikten sonraki tövbesine çok sevinir.',
    'Ne zaman uzaklaşsan, Rabbi\'nin seni çağırdığından emin ol.',
    'Bugün tökezlemen başarısızlığın anlamına gelmez, kalk ve diren.',
    'Asla pes etme, çünkü sen yorulmadıkça Allah yorulmaz.',
    'Hangi zamanda, hangi mekanda olursan ol, "Ey Rabbim" de O seninledir.'
  ];
}
