class DailyStatusQuotesFr {
  static const List<String> excellent = [
    'Saisissez ce qui reste du jour avec une intention sincère.',
    'Très proche de l\'achèvement, continuez sans vous arrêter.',
    'Ce qui reste est facile, et Allah vous ouvre la voie avec facilité.',
    'Quelques pas et vous atteindrez un jour spécial.',
    'Continuez ce que vous avez commencé, la belle fin est proche.',
    'Rassemblez le reste de votre journée dans l\'obéissance pour trouver l\'acceptation.',
    'C\'est ainsi que sont les bonnes journées : effort et constance.',
    'Faites des dernières heures de la journée les meilleures.',
    'Il reste peu de choses, ne reculez pas.',
    'Si vous avez bien fait la majeure partie de la journée, terminez-la avec excellence.',
    'Il reste encore de la place pour le bien dans votre journée, terminez-la.',
    'Allah regarde votre cœur sincère, alors finissez le travail avec amour.',
    'Vous avez accompli la partie la plus difficile, ne vous arrêtez pas maintenant.',
    'Tout ce que vous avez fait aujourd\'hui est magnifique, ne le gâchez pas par de la paresse à la fin.',
    'Hâtez-vous vers les bonnes actions ce soir, pour compléter la splendeur de votre journée.',
    'Chaque pas en avant vous rapproche des degrés du Paradis.',
  ];

  static const List<String> average = [
    'Ne désespérez pas de la miséricorde d\'Allah. En vérité, Allah pardonne tous les péchés.',
    'Chaque heure est une opportunité de revenir vers Allah.',
    'Allah se réjouit du repentir de Son serviteur, commencez maintenant.',
    'Commencez par ce que vous pouvez, car Allah aime le serviteur qui se tourne vers Lui.',
    'Le voyage commence par un pas, et votre pas aujourd\'hui est béni.',
    'La porte du rattrapage est ouverte tant qu\'il reste du temps dans la journée.',
    'Rendez le reste de votre journée plus sincère que ce qui est passé.',
    'N\'attendez pas l\'humeur, commencez et l\'aide vous viendra.',
    'Un bon début maintenant vaut mieux qu\'un retard constant.',
    'Chaque minute à venir est une opportunité de rattraper ce qui a été manqué.',
    'Tournez-vous vers Allah tel que vous êtes, Allah vous aidera.',
    'Si vous commencez maintenant, vous changez la forme de toute votre journée.',
    'L\'obéissance est toujours reprise et ses portes ne sont jamais fermées.',
    'Le meilleur n\'est pas passé, le meilleur commence maintenant.',
    'Cherchez l\'aide d\'Allah et ne soyez pas incapable du premier pas.',
    'Chaque retour vers Allah est compté et aimé.',
    'Commencez par ce qui est disponible aujourd\'hui, et Allah le bénira.',
    'La journée n\'est pas encore finie, rattrapez ce que vous avez manqué.',
    'La nuit est une couverture et une opportunité de rattrapage et de recueillement.',
    'C\'est maintenant le bon moment pour réparer votre journée par l\'obéissance.',
    'Ne vous contentez pas du milieu, élevez-vous pour atteindre la perfection possible.',
    'Éveillez votre détermination, vous pouvez encore rendre cette journée grandiose.',
    'Vous avez le pouvoir d\'effacer une mauvaise action par une bonne.',
  ];

  static const List<String> poor = [
    'En vérité, Allah est Pardonneur et Miséricordieux, ne désespérez pas.',
    'Ma miséricorde embrasse toute chose.',
    'Celui qui se repent du péché est comme celui qui n\'a pas de péché, revenez vers Allah.',
    'Commencez maintenant, même par une petite action, Allah vous ouvrira le cœur.',
    'Le chemin le plus proche d\'Allah est la sincérité du retour.',
    'Il vous suffit de commencer, et Allah achèvera le bien pour vous.',
    'La faiblesse disparaît avec la recherche fréquente de l\'aide d\'Allah.',
    'Aujourd\'hui est un nouveau départ, peu importe notre retard.',
    'Ne vous jugez pas sur une seule journée, recommencez à zéro.',
    'La porte de la miséricorde est large, ouvrez-la avec le repentir et l\'action.',
    'Le retour vers Allah ne nécessite qu\'une intention sincère.',
    'Si les faux pas sont nombreux, Allah est le plus Miséricordieux des miséricordieux.',
    'Commencez par un peu et ne méprisez aucune obéissance.',
    'Le vrai changement commence par la décision d\'aujourd\'hui.',
    'Ne laissez pas Satan vous priver d\'un début sincère.',
    'Celui qui réussit est celui qui revient rapidement chaque fois qu\'il faiblit.',
    'Soyez optimiste, car Allah accepte le repentir et aime ceux qui se repentent.',
    'Même si vous péchez à plusieurs reprises, revenez vers Allah à plusieurs reprises.',
    'Allah est plus heureux du repentir d\'un serviteur après qu\'il s\'est détourné.',
    'Chaque fois que vous vous éloignez, soyez sûr que votre Seigneur vous appelle.',
    'Votre trébuchement aujourd\'hui ne signifie pas votre échec, levez-vous et résistez.',
    'N\'abandonnez jamais, car Allah ne se lasse pas tant que vous ne vous lassez pas.',
    'À tout moment, n\'importe où, dites "Ô Seigneur" et Il est avec vous.',
  ];
}
