class DailyStatusQuotesEn {
  static const List<String> missedPrayers = [
    'Prayer is salvation, make it the first thing you return to today.',
    'If prayer feels heavy on the soul, know that your heart needs closeness.',
    'Establish your prayer, your day will be set right and your soul will find peace.',
    'Do not delay the door of mercy, the time of prayer is an open door.',
    'Every sincere prostration wipes away a long fatigue from the heart.',
    'Between you and tranquility is a sincere Takbeer.',
    'Returning to prayer is the beginning of fixing everything that follows.',
    'Allah calls you five times, so respond with a present heart.',
    'If your chest is tight, the place of relief is in prostration.',
    'Make prayer an appointment you do not compromise with the world.',
    'If you guard your prayer, Allah will guard the rest of your day.',
    'Prayer is the first reform of the soul and the greatest cause of steadfastness.',
    'Whoever is sincere in his prayer will find its impact throughout his day.',
    'A true return begins from the prayer rug.',
    'Do not carry the worries of tomorrow, perform your prayer today with excellence.',
    'During prostration, the heavy burdens of the heart fall away.',
    'When the soul is tired, its medicine is a humble prayer.',
    'The successful one makes prayer a red line in his day.',
    'Make every Adhan a message of mercy for you, not to be missed.',
    'Your prayer is the true measure of your steadfastness.',
    'If the caller calls, leave the world and turn to Allah.',
    'Prayer is the bridge of salvation in a crowded day.',
    'Maintain prayer, and Allah will open the doors of ease for you.',
    'A strong believer begins and ends their day with prayer.',
    'Tranquility resides in the heart of one who maintains the obligatory prayers.',
    'Do not be distracted from the foundation of your salvation: prayer.',
    'Every prayer on time is a step towards the pleasure of Allah.',
    'Perform the prayer as if it were your last covenant with the world.',
    'In prayer is the righteousness of the heart and the safety of the path.',
    'The journey of a thousand miles to Paradise begins with a prostration.'
  ];

  static const List<String> missedDhikr = [
    'Remember Allah and He will remember you; this is the greatest sufficiency.',
    'Dhikr is the life of the heart, do not deprive yourself of it.',
    'A minute of Dhikr builds the tranquility of a whole day.',
    'A tongue busy with Dhikr finds the coolness of peace.',
    'Begin and end your day with Allah.',
    'The remembrance of Allah is the closest, easiest, and most lasting fortress.',
    'If the heart is restless, stabilize it with seeking forgiveness and glorification.',
    'Those who remember Allah overtake others with light deeds but great impact.',
    'Increase your Dhikr, and the light of your heart will increase by Allah’s will.',
    'Glory be to Allah, a key to comfort that never rusts.',
    'Your daily Adhkar is your fortress, do not abandon it.',
    'How great is a heart that finds comfort in the remembrance of Allah.',
    'Multiply your Dhikr, you will find blessings in your time.',
    'With the remembrance of Allah, your hours become pleasant no matter the busyness.',
    'Seeking forgiveness erases stumbles and expands the chest.',
    'Make your tongue alive with Dhikr in all circumstances.',
    'Every glorification writes light and reward for you.',
    'Whoever sticks to Dhikr lives in tranquility.',
    'Your heart needs Dhikr just as the body needs water.',
    'Morning and evening Adhkar are the daily fence of faith.',
    'Do not let your day pass without a portion of Tasbih.',
    'The one who remembers is close to Allah at every moment.',
    'If the world narrows, flee to Dhikr.',
    'The remembrance of Allah revives the heart after heedlessness.',
    'Remember Me, I will remember you; a call waiting for you.',
    'Worries fall away with every seeking of forgiveness.',
    'The enduring good deeds are better than the world and what is in it.',
    'In the rush of life, do not neglect the enduring good deeds.',
    'A sincere Hawqala (There is no power nor strength except by Allah) may save you a lifetime of hardship.',
    'Fortify yourself with Dhikr, for devils flee from those who remember Allah.'
  ];

  static const List<String> missedWird = [
    'The Quran is your daily companion, do not leave your share of it.',
    'A few verses every day build a great steadfastness.',
    'Whoever sticks to the Quran, Allah fixes his inner and outer state.',
    'Do not deprive your heart of the blessing of recitation, even for minutes.',
    'Memorization is step by step, and the blessing is in continuation.',
    'The best investment of your day is a verse you memorize sincerely.',
    'Every Quranic Wird is a light added to your path.',
    'Connect your day to the Mushaf, and Allah will protect you from trials.',
    'Even a little of the Quran is much with Allah if it is continuous.',
    'Today’s verse might be tomorrow’s salvation.',
    'The Quran is the spring of hearts, do not abandon it.',
    'Every day with the Quran is an increase in light.',
    'Memorization starts with a verse and grows with steadfastness.',
    'Do not leave the Quran to complain about you one day.',
    'The Mushaf is a loyal companion to the one who stays with it.',
    'Accustom yourself to a Wird that you do not cut, no matter how small.',
    'The Quran purifies the soul and guides the path.',
    'No success in memorization without continuity.',
    'A verse memorized today is better than wishes without action.',
    'Daily recitation plants long-lasting tranquility.',
    'Connect your morning to the Quran, and Allah will make you steadfast.',
    'Keep a fixed time for your Wird every day.',
    'Whoever loves the Quran stays with it and does not abandon it.',
    'Make an appointment for the Quran that does not fall off your schedule.',
    'Do not stray from the spring, for the Quran is the water of your soul.',
    'And recite the Quran with measured recitation... make it the goal of your day.',
    'Every step closer to the Quran brings blessings closer to you.',
    'There is no happiness for one who abandons the words of his Creator.',
    'The Quran is a cure for what is in the breasts, how can you abandon your medicine?',
    'The best of you are those who learn the Quran and teach it... take your share of it.'
  ];

  static const List<String> perfect = [
    'Blessed is the one who does well in their day and ending.',
    'Successful indeed are the believers.',
    'May Allah accept, a day full of goodness.',
    'Indeed, the righteous will be in pleasure.',
    'Mashallah, your steadfastness today is a sign of sincerity.',
    'Your continuity is a great blessing, so thank Allah for it.',
    'This is a good day, ask Allah for acceptance and continuity.',
    'We ask Allah to bless this beautiful steadfastness.',
    'Goodness, when completed, is adorned with gratitude to Allah.',
    'Continuous obedience is among the most beautiful doors of closeness.',
    'How beautiful is a day where obedience and sincere intention meet.',
    'We ask Allah to perpetuate this beautiful steadfastness upon you.',
    'Your steadfastness today is a sign of success, so praise Allah.',
    'If you did well today, continue, and your reward will be multiplied.',
    'Every full day of obedience is a balance for the Hereafter.',
    'A good daily ending is a blessing that deserves gratitude.',
    'Congratulations to the one who ended his day close to Allah.',
    'Make this steadfastness a lifetime habit, not a daily mood.',
    'The successful servant is one who continues in obedience, even if it is little.',
    'May Allah record for you the reward of what you sought and completed.',
    'These are the days you will be pleased to see in your record.',
    'A little continuous deed is better than a lot interrupted... and you connected well.',
    'Praise be to Allah by Whose grace good deeds are completed.',
    'A day the angels boast about in the heavens... may Allah bless you.',
    'If you are grateful, I will surely increase you... so thank Allah for the completion of this favor.',
    'A day like this gives you glad tidings of mercy and a good ending.'
  ];

  static const List<String> good = [
    'Hasten to forgiveness from your Lord.',
    'O Allah, help us to remember You, thank You, and worship You well.',
    'Tomorrow is another opportunity by Allah’s will, do not stop.',
    'Little remains, complete your day with closeness to Allah.',
    'Few steps remain to complete the blessing of your day.',
    'Beautiful steadfastness, add a little completely and Allah will open much for you.',
    'You did well today, and continuous doing well is greater.',
    'Seize what remains of the day with a sincere intention.',
    'Very close to completion, continue without stopping.',
    'What remains is easy, and Allah opens with ease.',
    'A few steps and you reach a distinguished day.',
    'Secure what you started, for the beautiful ending is near.',
    'Gather the rest of your day on obedience, and you will gain acceptance.',
    'This is how good days are: effort and steadfastness.',
    'Make the last hours of the day the best of it.',
    'Only a little remains, do not retreat.',
    'If you did well most of the day, complete it with excellence.',
    'There is still room for goodness in your day, complete it.',
    'Allah looks at your sincere heart, so finish the work with love.',
    'You have accomplished the hardest part, do not stop now.',
    'Everything you did today is wonderful, do not spoil it with laziness at the end.',
    'Hasten to good deeds this evening, to complete the splendor of your day.',
    'Every step forward brings you closer to the degrees of Paradise.'
  ];

  static const List<String> average = [
    'Do not despair of the mercy of Allah. Indeed, Allah forgives all sins.',
    'Every hour is an opportunity to return to Allah.',
    'Allah rejoices in the repentance of His servant, start now.',
    'Start with what you can, Allah loves the servant who turns to Him.',
    'The journey begins with a step, and your step today is blessed.',
    'The door of making up is open as long as there is remnants in the day.',
    'Make the rest of your day more sincere than what has passed.',
    'Do not wait for the mood, start and help will come to you.',
    'A good start now is better than constant delay.',
    'Every coming minute is an opportunity to make up for what was missed.',
    'Turn to Allah as you are, Allah will help you.',
    'If you start now, you change the shape of your entire day.',
    'Obedience is always resumed and its doors are never closed.',
    'The best has not passed, the best begins now.',
    'Seek help from Allah and do not be incapable of the first step.',
    'Every return to Allah is counted and beloved.',
    'Start from what is available today, and Allah will bless it.',
    'The day is not over yet, catch up on what you missed.',
    'The night is a cover and an opportunity for catching up and seclusion.',
    'Now is the right time to repair your day with obedience.',
    'Do not settle for the middle, elevate yourself to reach the possible perfection.',
    'Awaken your determination, you can still make this day great.',
    'You have the power to push away a bad deed with a good one to wipe it out.'
  ];

  static const List<String> poor = [
    'Indeed, Allah is Forgiving and Merciful, do not despair.',
    'My mercy encompasses all things.',
    'The one who repents from sin is like the one without sin, return to Allah.',
    'Start now, even with a small deed, Allah will open your heart.',
    'The closest path to Allah is the sincerity of returning.',
    'It is enough for you to start, and Allah will complete the good for you.',
    'Weakness disappears with frequent seeking of Allah’s help.',
    'Today is a new beginning no matter how late we are.',
    'Do not judge yourself by a single day, start fresh.',
    'The door of mercy is wide, open it with repentance and action.',
    'Returning to Allah only requires a sincere intention.',
    'If stumbles are many, Allah is the Most Merciful of the merciful.',
    'Start with a little and do not belittle any obedience.',
    'True change begins with today’s decision.',
    'Do not let Satan deprive you of a sincere beginning.',
    'The successful one is the one who returns quickly whenever he slacks off.',
    'Be optimistic, for Allah accepts repentance and loves those who repent.',
    'Even if you sin repeatedly, return to Allah repeatedly.',
    'Allah is happier with the repentance of a servant after he turned away.',
    'Whenever you distance yourself, be sure that your Lord is calling you.',
    'Your stumbling today does not mean your failure, rise and resist.',
    'Never give up, for Allah does not tire until you tire.',
    'At any time, anywhere, say "Oh Lord" and He is with you.'
  ];
}
