class DailyStatusQuotesFr {
  static const List<String> missedPrayers = [
    'La prière est le salut, fais-en la première chose vers laquelle tu retournes aujourd\'hui.',
    'Si la prière te semble lourde, sache que ton cœur a besoin de proximité.',
    'Accomplis ta prière, ta journée s\'arrangera et ton âme trouvera la paix.',
    'Ne retarde pas la porte de la miséricorde, l\'heure de la prière est une porte ouverte.',
    'Chaque prosternation sincère efface la fatigue du cœur.',
    'Entre toi et la tranquillité, il y a un Takbeer sincère.',
    'Le retour à la prière est le début de la réparation de tout le reste.',
    'Allah t\'appelle cinq fois, réponds avec un cœur présent.',
    'Si ton cœur est serré, le lieu du soulagement est en prosternation.',
    'Fais de la prière un rendez-vous sur lequel tu ne transiges pas avec le monde.',
    'Si tu préserves ta prière, Allah préservera le reste de ta journée.',
    'La prière est la première réforme de l\'âme et la plus grande cause de constance.',
    'Celui qui est sincère dans sa prière en trouvera l\'impact tout au long de sa journée.',
    'Un véritable retour commence sur le tapis de prière.',
    'Ne porte pas les soucis de demain, accomplis ta prière aujourd\'hui avec excellence.',
    'Pendant la prosternation, les lourds fardeaux du cœur tombent.',
    'Quand l\'âme est fatiguée, son remède est une prière humble.',
    'Ceux qui réussissent font de la prière une ligne rouge dans leur journée.',
    'Fais de chaque Adhan un message de miséricorde pour toi, à ne pas manquer.',
    'Ta prière est la véritable mesure de ta constance.',
    'Si l\'appelant appelle, quitte le monde et tourne-toi vers Allah.',
    'La prière est le pont du salut dans une journée bien remplie.',
    'Maintenez la prière, et Allah vous ouvrira les portes de la facilité.',
    'Un croyant fort commence et termine sa journée par la prière.',
    'La tranquillité réside dans le cœur de celui qui maintient les prières obligatoires.',
    'Ne sois pas distrait du fondement de ton salut : la prière.',
    'Chaque prière à l\'heure est un pas vers le plaisir d\'Allah.',
    'Accomplis la prière comme si c\'était ta dernière alliance avec le monde.',
    'Dans la prière se trouve la droiture du cœur et la sécurité du chemin.',
    'Le voyage de mille kilomètres vers le Paradis commence par une prosternation.'
  ];

  static const List<String> missedDhikr = [
    'Souviens-toi d\'Allah et Il se souviendra de toi; c\'est la plus grande suffisance.',
    'Le Dhikr est la vie du cœur, ne t\'en prive pas.',
    'Une minute de Dhikr construit la tranquillité d\'une journée entière.',
    'Une langue occupée par le Dhikr trouve la fraîcheur de la paix.',
    'Commence et termine ta journée avec Allah.',
    'Le souvenir d\'Allah est la forteresse la plus proche, la plus facile et la plus durable.',
    'Si le cœur est agité, stabilise-le avec le pardon et la glorification.',
    'Ceux qui se souviennent d\'Allah devancent les autres avec des actes légers mais un grand impact.',
    'Augmente ton Dhikr, et la lumière de ton cœur augmentera par la volonté d\'Allah.',
    'Gloire à Allah, une clé de confort qui ne rouille jamais.',
    'Tes Adhkar quotidiens sont ta forteresse, ne les abandonne pas.',
    'Qu\'il est grand un cœur qui trouve le réconfort dans le souvenir d\'Allah.',
    'Multiplie ton Dhikr, tu trouveras des bénédictions dans ton temps.',
    'Avec le souvenir d\'Allah, tes heures deviennent agréables, peu importe l\'occupation.',
    'Demander pardon efface les trébuchements et élargit la poitrine.',
    'Rends ta langue vivante avec le Dhikr en toutes circonstances.',
    'Chaque glorification écrit de la lumière et une récompense pour toi.',
    'Quiconque s\'en tient au Dhikr vit dans la tranquillité.',
    'Ton cœur a besoin de Dhikr tout comme le corps a besoin d\'eau.',
    'Les Adhkar du matin et du soir sont la clôture quotidienne de la foi.',
    'Ne laisse pas ta journée passer sans une portion de Tasbih.',
    'Celui qui se souvient est proche d\'Allah à chaque instant.',
    'Si le monde se rétrécit, fuis vers le Dhikr.',
    'Le souvenir d\'Allah ravive le cœur après l\'insouciance.',
    'Souvenez-vous de Moi, Je me souviendrai de vous ; un appel qui vous attend.',
    'Les soucis tombent à chaque demande de pardon.',
    'Les bonnes actions durables valent mieux que le monde et ce qu\'il contient.',
    'Dans la précipitation de la vie, ne négligez pas les bonnes actions durables.',
    'Une Hawqala sincère peut vous épargner une vie de difficultés.',
    'Fortifiez-vous avec le Dhikr, car les démons fuient ceux qui se souviennent d\'Allah.'
  ];

  static const List<String> missedWird = [
    'Le Coran est ton compagnon quotidien, n\'en délaisse pas ta part.',
    'Quelques versets chaque jour construisent une grande constance.',
    'Quiconque s\'attache au Coran, Allah répare son état intérieur et extérieur.',
    'Ne prive pas ton cœur de la bénédiction de la récitation, même pour quelques minutes.',
    'La mémorisation se fait étape par étape, et la bénédiction réside dans la continuité.',
    'Le meilleur investissement de ta journée est un verset mémorisé sincèrement.',
    'Chaque Wird coranique est une lumière ajoutée à ton chemin.',
    'Relie ta journée au Mushaf, et Allah te protégera des épreuves.',
    'Même un peu de Coran est beaucoup auprès d\'Allah s\'il est continu.',
    'Le verset d\'aujourd\'hui pourrait être le salut de demain.',
    'Le Coran est le printemps des cœurs, ne l\'abandonne pas.',
    'Chaque jour avec le Coran est une augmentation de la lumière.',
    'La mémorisation commence par un verset et grandit avec la constance.',
    'Ne laisse pas le Coran se plaindre de toi un jour.',
    'Le Mushaf est un compagnon fidèle pour celui qui reste avec lui.',
    'Habitue-toi à un Wird que tu ne coupes pas, aussi petit soit-il.',
    'Le Coran purifie l\'âme et guide le chemin.',
    'Pas de succès dans la mémorisation sans continuité.',
    'Un verset mémorisé aujourd\'hui vaut mieux que des souhaits sans action.',
    'La récitation quotidienne plante une tranquillité durable.',
    'Connecte ton matin au Coran, et Allah te rendra ferme.',
    'Garde une heure fixe pour ton Wird chaque jour.',
    'Quiconque aime le Coran reste avec lui et ne l\'abandonne pas.',
    'Prends rendez-vous pour le Coran qui ne tombe pas de ton emploi du temps.',
    'Ne t\'éloigne pas de la source, car le Coran est l\'eau de ton âme.',
    'Et récite le Coran avec une récitation mesurée... fais-en le but de ta journée.',
    'Chaque pas vers le Coran rapproche les bénédictions de toi.',
    'Il n\'y a pas de bonheur pour celui qui abandonne les paroles de son Créateur.',
    'Le Coran est un remède à ce qui est dans les poitrines, comment peux-tu abandonner ton remède ?',
    'Les meilleurs d\'entre vous sont ceux qui apprennent le Coran et l\'enseignent... prenez-en votre part.'
  ];

  static const List<String> perfect = [
    'Heureux celui qui agit bien dans sa journée et à sa fin.',
    'Les croyants ont certes réussi.',
    'Qu\'Allah accepte, une journée pleine de bonté.',
    'Certes, les pieux seront dans les délices.',
    'Mashallah, ta constance aujourd\'hui est un signe de sincérité.',
    'Ta continuité est une grande bénédiction, remercie Allah pour cela.',
    'C\'est une belle journée, demande à Allah l\'acceptation et la continuité.',
    'Nous demandons à Allah de bénir cette belle constance.',
    'Le bien, lorsqu\'il est achevé, est embelli par la gratitude envers Allah.',
    'L\'obéissance continue est l\'une des plus belles portes de proximité.',
    'Qu\'il est beau un jour où l\'obéissance et l\'intention sincère se rencontrent.',
    'Nous demandons à Allah de perpétuer cette belle constance sur vous.',
    'Votre constance aujourd\'hui est un signe de succès, alors louez Allah.',
    'Si vous avez bien fait aujourd\'hui, continuez et votre récompense sera multipliée.',
    'Chaque journée complète d\'obéissance est un équilibre pour l\'Au-delà.',
    'Une bonne fin quotidienne est une bénédiction qui mérite gratitude.',
    'Félicitations à celui qui a terminé sa journée près d\'Allah.',
    'Faites de cette constance une habitude à vie, pas une humeur quotidienne.',
    'Le serviteur prospère est celui qui continue dans l\'obéissance, même si c\'est peu.',
    'Qu\'Allah enregistre pour vous la récompense de ce que vous avez cherché et accompli.',
    'Ce sont les jours que vous serez heureux de voir dans votre dossier.',
    'Une petite action continue vaut mieux que beaucoup interrompues... et vous vous êtes bien connecté.',
    'Louange à Allah par la grâce de qui les bonnes actions sont accomplies.',
    'Un jour dont les anges se vantent dans les cieux... qu\'Allah vous bénisse.',
    'Si vous êtes reconnaissants, Je vous augmenterai sûrement... alors remerciez Allah pour l\'achèvement de cette faveur.',
    'Un jour comme celui-ci vous annonce de bonnes nouvelles de miséricorde et d\'une bonne fin.'
  ];

  static const List<String> good = [
    'Hâtez-vous vers le pardon de votre Seigneur.',
    'Ô Allah, aide-nous à Te mentionner, à Te remercier et à parfaire Ton adoration.',
    'Demain est une autre opportunité avec la permission d\'Allah, ne t\'arrête pas.',
    'Il reste peu, complète ta journée en te rapprochant d\'Allah.',
    'Peu d\'étapes restent pour compléter la bénédiction de ta journée.',
    'Belle constance, ajoute un peu et Allah t\'ouvrira beaucoup.',
    'Tu as bien agi aujourd\'hui, et la continuité du bien est encore meilleure.',
    'Saisis ce qui reste de la journée avec une intention sincère.',
    'Très proche de l\'achèvement, continue sans t\'arrêter.',
    'Ce qui reste est facile, et Allah ouvre avec facilité.',
    'Quelques pas et vous atteignez une journée distinguée.',
    'Sécurisez ce que vous avez commencé, car la belle fin est proche.',
    'Rassemblez le reste de votre journée sur l\'obéissance et vous obtiendrez l\'acceptation.',
    'C\'est ainsi que sont les bons jours : effort et constance.',
    'Faites des dernières heures de la journée les meilleures.',
    'Il ne reste que peu, ne reculez pas.',
    'Si vous avez bien fait la majeure partie de la journée, complétez-la avec excellence.',
    'Il reste encore de la place pour la bonté dans votre journée, complétez-la.',
    'Allah regarde votre cœur sincère, alors terminez le travail avec amour.',
    'Vous avez accompli la partie la plus difficile, ne vous arrêtez pas maintenant.',
    'Tout ce que vous avez fait aujourd\'hui est merveilleux, ne le gâchez pas par la paresse à la fin.',
    'Hâtez-vous vers les bonnes actions ce soir, pour compléter la splendeur de votre journée.',
    'Chaque pas en avant vous rapproche des degrés du Paradis.'
  ];

  static const List<String> average = [
    'Ne désespérez pas de la miséricorde d\'Allah. Certes, Allah pardonne tous les péchés.',
    'Chaque heure est une opportunité de retourner à Allah.',
    'Allah se réjouit du repentir de Son serviteur, commence maintenant.',
    'Commence par ce que tu peux, Allah aime le serviteur qui se tourne vers Lui.',
    'Le voyage commence par un pas, et ton pas aujourd\'hui est béni.',
    'La porte du rattrapage est ouverte tant qu\'il reste du jour.',
    'Rends le reste de ta journée plus sincère que ce qui est passé.',
    'N\'attends pas d\'être d\'humeur, commence et l\'aide viendra à toi.',
    'Un bon départ maintenant vaut mieux qu\'un retard constant.',
    'Chaque minute à venir est une occasion de rattraper ce qui a été manqué.',
    'Tournez-vous vers Allah tel que vous êtes, Allah vous aidera.',
    'Si vous commencez maintenant, vous modifiez la forme de toute votre journée.',
    'L\'obéissance reprend toujours et ses portes ne se ferment jamais.',
    'Le meilleur n\'est pas passé, le meilleur commence maintenant.',
    'Demandez l\'aide d\'Allah et ne soyez pas incapable du premier pas.',
    'Chaque retour à Allah est compté et aimé.',
    'Commencez par ce qui est disponible aujourd\'hui et Allah le bénira.',
    'La journée n\'est pas encore terminée, rattrapez ce que vous avez manqué.',
    'La nuit est une couverture et une opportunité de rattrapage et de solitude.',
    'C\'est maintenant le bon moment pour réparer votre journée avec l\'obéissance.',
    'Ne vous contentez pas du milieu, élevez-vous pour atteindre la perfection possible.',
    'Réveillez votre détermination, vous pouvez encore rendre cette journée formidable.',
    'Vous avez le pouvoir de repousser une mauvaise action avec une bonne pour l\'effacer.'
  ];

  static const List<String> poor = [
    'Certes, Allah est Pardonneur et Miséricordieux, ne désespère pas.',
    'Ma miséricorde embrasse toute chose.',
    'Celui qui se repent du péché est comme celui qui n\'a pas de péché, retourne à Allah.',
    'Commence maintenant, même par une petite action, Allah ouvrira ton cœur.',
    'Le chemin le plus proche d\'Allah est la sincérité du retour.',
    'Il te suffit de commencer, et Allah complètera le bien pour toi.',
    'La faiblesse disparaît en cherchant souvent l\'aide d\'Allah.',
    'Aujourd\'hui est un nouveau départ, peu importe le retard.',
    'Ne te juge pas sur une seule journée, recommence.',
    'La porte de la miséricorde est grande, ouvre-la avec le repentir et l\'action.',
    'Revenir à Allah ne nécessite qu\'une intention sincère.',
    'Si les trébuchements sont nombreux, Allah est le Plus Miséricordieux des miséricordieux.',
    'Commencez par un peu et ne minimisez aucune obéissance.',
    'Le vrai changement commence avec la décision d\'aujourd\'hui.',
    'Ne laissez pas Satan vous priver d\'un commencement sincère.',
    'Celui qui réussit est celui qui revient rapidement chaque fois qu\'il se relâche.',
    'Soyez optimiste, car Allah accepte le repentir et aime ceux qui se repentent.',
    'Même si vous péchez à plusieurs reprises, retournez à Allah à plusieurs reprises.',
    'Allah est plus heureux du repentir d\'un serviteur après qu\'il s\'est détourné.',
    'Chaque fois que vous vous éloignez, soyez sûr que votre Seigneur vous appelle.',
    'Votre trébuchement d\'aujourd\'hui ne signifie pas votre échec, levez-vous et résistez.',
    'N\'abandonnez jamais, car Allah ne se fatigue pas jusqu\'à ce que vous vous fatiguiez.',
    'À tout moment, n\'importe où, dites "Oh Seigneur" et Il est avec vous.'
  ];
}
