class DailyStatusQuotesEn {
  static const List<String> excellent = [
    'Seize what remains of the day with a sincere intention.',
    'Very close to completion, continue without stopping.',
    'What remains is easy, and Allah opens the way for you with ease.',
    'A few steps and you will reach a special day.',
    'Keep up what you started, the beautiful end is near.',
    'Gather the rest of your day in obedience to find acceptance.',
    'This is how good days are: effort and steadfastness.',
    'Make the last hours of the day the best of it.',
    'Only a little remains, do not retreat.',
    'If you did well most of the day, complete it with excellence.',
    'There is still room for goodness in your day, complete it.',
    'Allah looks at your sincere heart, so finish the work with love.',
    'You have accomplished the hardest part, do not stop now.',
    'Everything you did today is wonderful, do not spoil it with laziness at the end.',
    'Hasten to good deeds this evening, to complete the splendor of your day.',
    'Every step forward brings you closer to the degrees of Paradise.',
  ];

  static const List<String> average = [
    'Do not despair of the mercy of Allah. Indeed, Allah forgives all sins.',
    'Every hour is an opportunity to return to Allah.',
    'Allah rejoices in the repentance of His servant, start now.',
    'Start with what you can, Allah loves the servant who turns to Him.',
    'The journey begins with a step, and your step today is blessed.',
    'The door of making up is open as long as there is remnants in the day.',
    'Make the rest of your day more sincere than what has passed.',
    'Do not wait for the mood, start and help will come to you.',
    'A good start now is better than constant delay.',
    'Every coming minute is an opportunity to make up for what was missed.',
    'Turn to Allah as you are, Allah will help you.',
    'If you start now, you change the shape of your entire day.',
    'Obedience is always resumed and its doors are never closed.',
    'The best has not passed, the best begins now.',
    'Seek help from Allah and do not be incapable of the first step.',
    'Every return to Allah is counted and beloved.',
    'Start from what is available today, and Allah will bless it.',
    'The day is not over yet, catch up on what you missed.',
    'The night is a cover and an opportunity for catching up and seclusion.',
    'Now is the right time to repair your day with obedience.',
    'Do not settle for the middle, elevate yourself to reach the possible perfection.',
    'Awaken your determination, you can still make this day great.',
    'You have the power to push away a bad deed with a good one to wipe it out.',
  ];

  static const List<String> poor = [
    'Indeed, Allah is Forgiving and Merciful, do not despair.',
    'My mercy encompasses all things.',
    'The one who repents from sin is like the one without sin, return to Allah.',
    'Start now, even with a small deed, Allah will open your heart.',
    'The closest path to Allah is the sincerity of returning.',
    'It is enough for you to start, and Allah will complete the good for you.',
    'Weakness disappears with frequent seeking of Allah\'s help.',
    'Today is a new beginning no matter how late we are.',
    'Do not judge yourself by a single day, start fresh.',
    'The door of mercy is wide, open it with repentance and action.',
    'Returning to Allah only requires a sincere intention.',
    'If stumbles are many, Allah is the Most Merciful of the merciful.',
    'Start with a little and do not belittle any obedience.',
    'True change begins with today\'s decision.',
    'Do not let Satan deprive you of a sincere beginning.',
    'The successful one is the one who returns quickly whenever he slacks off.',
    'Be optimistic, for Allah accepts repentance and loves those who repent.',
    'Even if you sin repeatedly, return to Allah repeatedly.',
    'Allah is happier with the repentance of a servant after he turned away.',
    'Whenever you distance yourself, be sure that your Lord is calling you.',
    'Your stumbling today does not mean your failure, rise and resist.',
    'Never give up, for Allah does not tire until you tire.',
    'At any time, anywhere, say "Oh Lord" and He is with you.',
  ];
}
