// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYP5_MO8z_2e7qdA5HYdelkdeR_mXlzFY',
    appId: '1:280683229836:web:818a3900314e37579401a9',
    messagingSenderId: '280683229836',
    projectId: 'sura-98979',
    authDomain: 'sura-98979.firebaseapp.com',
    storageBucket: 'sura-98979.firebasestorage.app',
    measurementId: 'G-255L54WY6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA492CFIgqQ5FiA3XWXBPnVhO77n7i-hJs',
    appId: '1:280683229836:android:83840db4a9f4fadc9401a9',
    messagingSenderId: '280683229836',
    projectId: 'sura-98979',
    storageBucket: 'sura-98979.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5OPXPiOMCh83UtJje3L1kDL7dOcehQH0',
    appId: '1:280683229836:ios:d5c978a01ac80f0a9401a9',
    messagingSenderId: '280683229836',
    projectId: 'sura-98979',
    storageBucket: 'sura-98979.firebasestorage.app',
    iosBundleId: 'com.sura.app.suraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5OPXPiOMCh83UtJje3L1kDL7dOcehQH0',
    appId: '1:280683229836:ios:4fc01f725cad2c289401a9',
    messagingSenderId: '280683229836',
    projectId: 'sura-98979',
    storageBucket: 'sura-98979.firebasestorage.app',
    iosBundleId: 'com.Sura.app.SuraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYP5_MO8z_2e7qdA5HYdelkdeR_mXlzFY',
    appId: '1:280683229836:web:40a0f12d39ae47d79401a9',
    messagingSenderId: '280683229836',
    projectId: 'sura-98979',
    authDomain: 'sura-98979.firebaseapp.com',
    storageBucket: 'sura-98979.firebasestorage.app',
    measurementId: 'G-0J8Z8FPCQT',
  );
}
