name: sila_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Data & Network
  path_provider: ^2.1.1
  fpdart: ^1.1.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  shared_preferences: ^2.5.4

  # UI & Localization
  easy_localization: ^3.0.3
  google_fonts: ^6.1.0
  just_audio: ^0.10.5
  adhan: ^2.0.0+1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  http: ^1.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/data/
